[Middleware_01] Made Processor Implementation, Tests and Manager Stub
andrewdimmer/csi-3370-software-project pull request #125
Opened 2020-11-29 22:29 UTC by juliawang2014

Fixes #69

2020-11-29 22:41 UTC, brendam19 approved these changes

2020-11-29 23:57 UTC, andrewdimmer requested changes
One minor fix then you're all set to merge!

2020-11-29 23:57 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/middleware01/MiddlewareGisManagerStub.java
> +    return "GPS0";
This shouldn't be hard coded, but should instead be used to verify that basically the correct satellite was sent in. (Basically the same as how you do it above.)
```suggestion
    return satellite.getSatelliteName();
```

2020-11-30 00:06 UTC, andrewdimmer approved these changes
Looks good to me, you are all set to merge!

2020-11-30 00:07 UTC, merged