Build DisplayGpsReceiverImplementationTests
andrewdimmer/csi-3370-software-project pull request #126
Opened 2020-11-29 22:36 UTC by EC01EC

Working on #67

2020-11-30 09:25 UTC, andrewdimmer requested changes
Great start so far! The production code looks good just in terms of a quick read though, we just need to make sure we've got test coverage for it. Based on the code that we have here, there are 4 more tests that you'll need to cover the rest of the production code:

- [x] measureGpsSignalStrengthSatelliteSignalNotNull()
- [ ] measureGpsSignalStrengthSignalInIsSignalOut()
- [ ] measureSignalSatelliteSignalNotNull()
- [ ] measureSignalSignalInIsSignalOut()

To complete these tests, you'll create a new class in the `edu.oakland.test.display01` package called `DisplayGisManagerStub` that implements the `DisplayGisManager` Java interface. For each method defined in the `DisplayGisManagerStub` based on the interface, you'll create and return a new `SatelliteSignalCheckRequest` object with the name of the input satellite as the name of the satellite in the aforementioned output object.

From there, you can simply add the methods for the 4 test cases above.

For each of the "Not Null" cases create a new instance of `DisplayGpsReceiverImplementation` with an instance of `DisplayGisManagerStub` passed in via the constructor, then call the appropriate method based on the test name from within the `assertThrows` test as you currently do for `displayGpsManagerIsNotNull()`. 

For each of the "In Is Out" cases create a new instance of `DisplayGpsReceiverImplementation` with an instance of `DisplayGisManagerStub` passed in via the constructor. Then, you'll create a Satellite object with a non-empty name, and call the appropriate method based on the test name from within the `assertEquals` test to verify that `inputSatellite.getSatelliteName()` is equal to `displayGpsReceiver.methodHere(inputSatellite).getSatelliteName()`. 

If you have any issues or questions, feel free to reach out!

2020-11-30 09:25 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/Display01/DisplayGpsReceiverImplementation/DisplayGpsReceiverImplementationTests.java
> +@DisplayName ("Display GPS Receiver Implementation")
For sake of standardization to make it easier to read and search the logs, can we change this to `DisplayGpsReceiverImplementation Unit Tests`? Thank you!
```suggestion
@DisplayName ("DisplayGpsReceiverImplementation Unit Tests")
```

2020-11-30 09:25 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display01/DisplayGpsReceiverImplementation.java
> +      throw new IllegalArgumentException("Signal strength cannot be null");
Just to make this exception a little more descriptive, can we change the output to the name of the parameter? Thank you!
```suggestion
      throw new IllegalArgumentException("satelliteSignal cannot be null");
```

2020-11-30 09:25 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display01/DisplayGpsReceiverImplementation.java
> +      throw new IllegalArgumentException("Signal strength cannot be null");
Just to make this exception a little more descriptive, can we change the output to the name of the parameter? Thank you!
```suggestion
      throw new IllegalArgumentException("satelliteSignal cannot be null");
```

2020-12-01 05:05 UTC, stevecatherman approved these changes
Great success!

2020-12-01 05:26 UTC, andrewdimmer requested changes
Few minor comments, mostly around formatting, then you're all set to merge!

2020-12-01 05:26 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display01/DisplayGpsReceiverImplementation.java
> +      throw new IllegalArgumentException("Signal strength cannot be null");
This is actually checking the manager, not the signal strength.
```suggestion
      throw new IllegalArgumentException("displayGpsManager cannot be null");
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsManagerStub.java
> +    return ssrc.getSatelliteName();
This just needs to return a string, so we can streamline it as follows:
```suggestion
    return satelliteSignal.getSatelliteName();
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsManagerStub.java
> +        new SatelliteSignalCheckRequest(satelliteSignal.getSatelliteName(), checkType);
Just a little cleaner formatting:
```suggestion
    SatelliteSignalCheckRequest ssrc = new SatelliteSignalCheckRequest(
        satelliteSignal.getSatelliteName(),
        checkType
    );
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsReceiverImplementationTests.java
> +        new DisplayGpsReceiverImplementation(new DisplayGpsManagerStub());
Just a little cleaner formatting:
```suggestion
    DisplayGpsReceiverImplementation d = new DisplayGpsReceiverImplementation(
        new DisplayGpsManagerStub()
    );
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsReceiverImplementationTests.java
> +        new DisplayGpsReceiverImplementation(new DisplayGpsManagerStub());
Just a little cleaner formatting:
```suggestion
    DisplayGpsReceiverImplementation d = new DisplayGpsReceiverImplementation(
        new DisplayGpsManagerStub()
    );
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsReceiverImplementationTests.java
> +        new DisplayGpsReceiverImplementation(new DisplayGpsManagerStub());
Just a little cleaner formatting:
```suggestion
    DisplayGpsReceiverImplementation d = new DisplayGpsReceiverImplementation(
        new DisplayGpsManagerStub()
    );
```

2020-12-01 05:26 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/DisplayGpsReceiverImplementationTests.java
> +        new DisplayGpsReceiverImplementation(new DisplayGpsManagerStub());
Just a little cleaner formatting:
```suggestion
    DisplayGpsReceiverImplementation d = new DisplayGpsReceiverImplementation(
        new DisplayGpsManagerStub()
    );
```

2020-12-01 05:32 UTC, andrewdimmer approved these changes
Looks good to me, you're all set to merge provided checks pass!

2020-12-01 05:32 UTC, merged