[Display_02] DisplayCommInterface Test and Implementation
andrewdimmer/csi-3370-software-project pull request #134
Opened 2020-11-30 02:17 UTC by Dbaker19972

2020-11-30 16:13 UTC, sydneyhill3901 requested changes
Go ahead and make the style changes requested by the bot when you get the chance, and I'll take another look at it later.

2020-11-30 21:12 UTC, andrewdimmer commented
### NOTE: DO NOT COMMIT THE `/bin/` FOLDER!

This effectively doubles the size of the repo and breaks a whole bunch of stuff. I've fixed it now, I just wanted to let everyone on this branch know that one of you will likely be prompted to commit it now that it is untracked again, but please don't.

2020-12-01 00:18 UTC, andrewdimmer approved these changes
One minor change then you're all set to merge!

2020-12-01 00:18 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayCommInterfaceImplementation.java
> +      throw new IllegalArgumentException("processor cannot be null");
This should be as follows, as it's not really the processor:
```suggestion
      throw new IllegalArgumentException("displayComm2WayInterface cannot be null");
```

2020-12-01 00:29 UTC, sydneyhill3901 approved these changes

2020-12-01 00:29 UTC, sydneyhill3901 commented on src/main/java/edu/oakland/production/display02/DisplayCommInterface.java
> -
Good to merge.

2020-12-01 00:31 UTC, merged