[Database] Build Database Comm Interface
andrewdimmer/csi-3370-software-project pull request #138
Opened 2020-11-30 04:38 UTC by MathewYaldo

2020-11-30 18:44 UTC, andrewdimmer requested changes
I've made a number of suggestions to help you get started fixing the testing. If you want to go through and accept my suggestions directly, feel free to. You can also accept as many or as few as you'd like in a batch from https://github.com/andrewdimmer/csi-3370-software-project/pull/138/files, by adding each suggestion you want to add to a batch, then committing the whole batch all at once from the green commit button at the top of the page.

Note that my suggestions are just fixing the lines they are on; you'll likely need to fix additional things like imports or references on other lines to get everything to compile again. They should provide a baseline to model how to do the first two tests though, so you can apply the same techniques to the last two. Let me know if you have any questions, and I'd be happy to provide more info if you need it!

2020-11-30 18:44 UTC, andrewdimmer commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
This is a IDE config file and should be removed from the PR.

2020-11-30 18:44 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/database/DatabaseCommInterfaceClass.java
> +public class DatabaseCommInterfaceClass {
This should be updated to comply with the naming conventions that were laid out in the UML Class Diagrams. You also need to make sure that you implement the `DatabaseCommInterface` Java interface.
```suggestion
public class DatabaseCommInterfaceImplementation implements DatabaseCommInterface {
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +public class DatabaseCommInterfaceTest {
For sake of standardization to make it easier to read and search the logs, can we change this to `DatabaseCommInterfaceImplementation Unit Tests`? Thank you!
```suggestion
@DisplayName("DatabaseCommInterfaceImplementation Unit Tests")
public class DatabaseCommInterfaceImplementationTests {
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommManagerStub.java
> +  int rfid = 10;
Let's make sure that this is private!
```suggestion
  private int rfid;
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommManagerStub.java
> +
Can we add a way to set the RFID number? One way to do it is via constructor (as suggested), or you could also do this via a setter.
```suggestion

  public DatabaseCommManagerStub(int rfid) {
    this.rfid = rfid;
  }

```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +    int i = 10;
Let's make this random to increase test robustness:
```suggestion
    int i = (int) (Math.random() * 100);
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +    assertEquals(i, dcm.passGetRfidRequest());
For test classes, make sure that you're running the test on the class you want to test. Below is an example of how to use the stub in relation to the class you want to test.
```suggestion
    DatabaseCommManagerStub dcm = new DatabaseCommManagerStub(i);
    DatabaseCommInterface dci = new DatabaseCommInterfaceImpementation(dcm);
    assertEquals(i, dci.receiveGetRfidRequest());
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +    ldp = null;
We shouldn't be setting what we just randomly generated to `null`. `null` is an edge case that should be handled separately, and should not be used as a default test case. Instead, let's pass our randomly generated `LocationDataPoint` to the the `DatabaseCommManagerStub`. You may need to add a setter to the stub to do this.

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +    assertEquals(ldp, dcm.passGetLocationDataPointRequest(i));
```suggestion
    assertEquals(ldp, dci.receiveGetLocationDataPointRequest(i));
```

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +  void offsetMatchTrackData() {
Can you model this test off of the ones above it?

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +  void trackDataInIsTrackDataOut() {
Can you model this test off of the ones above it?

2020-11-30 18:44 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +  void modeInIsModeOut() {
Can you model this test off of the ones above it?

2020-12-01 02:04 UTC, kylepoterek approved these changes

2020-12-01 03:11 UTC, andrewdimmer requested changes
Few tiny changes, but once you take a look at those you are set to merge!

2020-12-01 03:11 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommManagerStub.java
> +  String mode = "";
```suggestion
  private int rfid;
  private LocationDataPoint ldp = null;
  private int index = 0;
  private TrackData td = null;
  private String mode = "";
```

2020-12-01 03:11 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/database/DatabaseCommInterfaceTest.java
> +    td = null;
Make sure you're not setting this to null, null is an edge case, not a normal case we want to handle.
```suggestion
```

2020-12-01 03:15 UTC, andrewdimmer approved these changes
Just update the branch and you're all set to merge!

2020-12-01 03:19 UTC, merged