[Display_02] Built DisplayComm2WayInterfaceImplementationTests.java
andrewdimmer/csi-3370-software-project pull request #141
Opened 2020-11-30 06:07 UTC by jmccloud827

2020-11-30 15:59 UTC, sydneyhill3901 requested changes
Try to address the errors and style issues listed, if you need help I will be available to work on this later today.

2020-11-30 20:44 UTC, jcortes18 commented on src/main/java/edu/oakland/production/display02/DisplayComm2WayInterfaceImplementation.java
> +  * @param DisplayCommManagerImplementation: The class that DisplayComm2Way will pass RFID to.
I think this should work once DisplayCommManagerImplementation is merged

2020-11-30 22:48 UTC, jcortes18 commented
Some errors in the test class. Please review, thanks!

2020-12-01 01:09 UTC, Volter43 approved these changes

2020-12-01 02:03 UTC, andrewdimmer requested changes
Few recommendations to streamline your production code, and one missing test. Details are down below, and you should be able to find examples of the test in other test classes.

2020-12-01 02:03 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayComm2WayInterfaceImplementation.java
> +      throw new IllegalArgumentException("cannot be null");
Please make this more descriptive as to where the error is coming from.
```suggestion
      throw new IllegalArgumentException("displayCommManager cannot be null");

```

2020-12-01 02:03 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayComm2WayInterfaceImplementation.java
> +  }
Let's see if we can streamline this. I think we can remove all of this, correct? At the very least this needs to be private if you want to keep it.
```suggestion
```

2020-12-01 02:03 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayComm2WayInterfaceImplementation.java
> +    return passRfidRequest(rfidNum);
Let's see if we can streamline this. I think we can remove all of the private methods that are just pass throughs, right?
```suggestion
    return commManager.evaluateRfidRequest(rfidNum);

```

2020-12-01 02:03 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display02/DisplayComm2WayInterfaceImplementationTests.java
> +import static org.junit.jupiter.api.Assertions.assertThrows;
You need to make a method to test that the RFID method is passed in and a track data is passed, and checks that the status message of the TrackData is the output. That should finish your test coverage, and there are other examples of this merged into main if you look around in other Comm classes. Let me know if you have any other questions, and I'd be happy to help!

2020-12-01 05:16 UTC, sydneyhill3901 approved these changes
Looks good to me.

2020-12-01 05:16 UTC, sydneyhill3901 commented on src/test/java/edu/oakland/test/display02/DisplayComm2WayInterfaceImplementationTests.java
> +  @Test
Glad you were able to figure out those coverage checks. Approving.

2020-12-01 17:28 UTC, andrewdimmer approved these changes
Looks good to me! You're all set to merge!

2020-12-01 17:41 UTC, merged