[Display-01] Standardized name of SatelliteSignalCheckRequest
andrewdimmer/csi-3370-software-project pull request #147
Opened 2020-11-30 19:40 UTC by casher-ou

2020-11-30 21:55 UTC, andrewdimmer requested changes

2020-11-30 21:55 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/SatelliteSignalCheckRequestUnitTests.java
> +public class SatelliteSignalCheckRequestUnitTests {
The class name was fine. That should be changed back.
```suggestion
public class SatelliteSignalCheckRequestTests {
```

2020-11-30 21:55 UTC, andrewdimmer commented on src/test/java/edu/oakland/test/display01/SatelliteSignalCheckRequestUnitTests.java
>  @DisplayName("Sattelite Signal Check Request Tests")
This was the part that needed to be updated.
```suggestion
@DisplayName("SatelliteSignalCheckRequest Unit Tests")
```

2020-12-01 00:35 UTC, andrewdimmer approved these changes
Thank you, all set to merge!

2020-12-01 01:14 UTC, stevecatherman approved these changes
:)

2020-12-01 03:00 UTC, merged