Update display comm interface implementation class
andrewdimmer/csi-3370-software-project pull request #155
Opened 2020-12-02 22:42 UTC by jcortes18

2020-12-02 22:57 UTC, jcortes18 commented
I think it's not passing the gradle tests because TrackDataPlotter hasn't been merged into main.

2020-12-03 01:07 UTC, andrewdimmer requested changes
Couple of quick changes, then I'd like to take over and add some testing, then you should be good to go!

2020-12-03 01:07 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayCommInterfaceImplementation.java
> +  private TrackDataPlotter plotter;
These don't need to be stored at the class level as they are only used at the method level.
```suggestion
```

2020-12-03 01:07 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayCommInterfaceImplementation.java
> +    this.data = comm2Way.passRfidRequest(rfidNum);
If we remove the above private class attributes, then this gets the type added to it.
```suggestion
    TrackData data = comm2Way.passRfidRequest(rfidNum);
```

2020-12-03 01:07 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayCommInterfaceImplementation.java
> +    System.out.println("Status: " + data.getStatusMessage());
This should be moved to the `toString()` method of TrackData itself. I would also recommend printing the status message first, then the speed and course IF the `TrackData` object is valid, then the points at the end.

2020-12-03 01:07 UTC, andrewdimmer commented on src/main/java/edu/oakland/production/display02/DisplayCommInterfaceImplementation.java
> +    this.plotter = new TrackDataPlotter(data);
If we remove the above private class attributes, then this gets the type added to it.
```suggestion
    TrackDataPlotter plotter = new TrackDataPlotter(data);
```

2020-12-03 01:07 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/LocationDataPoint.java
> +    return lat + " " + lng + " " + time;
I would see if you can make this more descriptive, may something like:
```suggestion
    return "Location Data at " + time.toString() + ":\n\tLatitude: " + lat + "\n\tLongitude: " + lng;
```

2020-12-03 02:13 UTC, andrewdimmer requested changes
Few more minor changes, but once you do this you're all set!

2020-12-03 02:13 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/LocationDataPoint.java
I would make sure you add the `@Override notation and a Javadoc
```suggestion
  /**
   * Creates a print-friendly string of the LocationDataPoint data.
   *
   * @return The print friendly string of the LocationDataPoint data.
   */
  @Override
```

2020-12-03 02:13 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/TrackData.java
> +  @Override
I would add the following Javadoc here:
```suggestion
  /**
   * Creates a print-friendly string of the TrackData data.
   *
   * @return The print friendly string of the TrackData data.
   */
  @Override
```

2020-12-03 02:13 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/TrackData.java
> +      System.out.println("Status: " + getStatusMessage());
It should always print the status, even if it is not valid.
```suggestion
    str.append("Track Data Status: " + getStatusMessage() + "\n");
    if (isValid()) {
```

2020-12-03 02:13 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/TrackData.java
> +      System.out.println("Course Direction: " + getCourseDirection());
Make sure these get appended to the output!
```suggestion
      str.append("Speed: " + getSpeed() + "\n");
      str.append("Course Direction: " + getCourseDirection() + "\n");
```

2020-12-03 02:16 UTC, andrewdimmer commented on src/main/java/edu/oakland/helper/admin/LocationDataPoint.java
> +  @Override
Oops! My bad... let me fix this one...

2020-12-03 02:27 UTC, andrewdimmer approved these changes
Looks good to me! I'm going to fix the last of the test issues caused by the Plotter, then this is set to merge!

2020-12-03 05:55 UTC, andrewdimmer approved these changes
Now, we're all set to merge if everyone else agrees.

2020-12-03 05:57 UTC, sydneyhill3901 approved these changes

2020-12-03 05:58 UTC, merged