[Display_01] Define DisplayGpsReceiverImplementationTests
andrewdimmer/csi-3370-software-project pull request #92
Opened 2020-11-28 03:28 UTC by EC01EC

Created test methods for DisplayGpsReceiverImplementationTests.puml

2020-11-28 23:36 UTC, andrewdimmer requested changes
One minor change, then you're set to merge!

2020-11-28 23:36 UTC, andrewdimmer commented on docs/uml-class-diagrams/display01/test/DisplayGpsReceiverImplementationTests/DisplayGpsReceiverImplementationTests.puml
> +        + void elseSignalStrengthBadRejectSignal()
Make sure you have a check that the next link in the chain is not missing!
```suggestion
        + void elseSignalStrengthBadRejectSignal()
        + void displayGpsManagerIsNotNull()
```

2020-11-29 01:47 UTC, andrewdimmer approved these changes
Looks good to me, you're all set to merge!

2020-11-29 19:40 UTC, stevecatherman approved these changes
:)

2020-11-29 19:50 UTC, merged