[Display_01] Define DisplayGpsManagerImplementationTests
andrewdimmer/csi-3370-software-project pull request #93
Opened 2020-11-28 05:16 UTC by atpoynter

Working on #56

2020-11-28 23:38 UTC, andrewdimmer requested changes

2020-11-28 23:38 UTC, andrewdimmer commented on docs/uml-class-diagrams/display01/test/DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests.puml
> +        +
Where is the if statement in your code? I think that #92 currently looks like it does the signal check, but neither does null checking...

2020-11-29 16:22 UTC, EC01EC approved these changes
Null checking resolved in #92. Looks good

2020-11-29 18:35 UTC, andrewdimmer requested changes
The fix for #74 looks good in the code, but make sure you update the interface and implementation docs as well. Also, make sure that finish adding the test methods!

2020-11-29 18:35 UTC, andrewdimmer commented on docs/uml-class-diagrams/display01/test/DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests.puml
> +package edu.oakland.display01.tests {
This is the package that your java class goes in, and was correct before.
```suggestion
package edu.oakland.test.display01 {
```

2020-11-29 19:36 UTC, EC01EC approved these changes
good

2020-11-29 19:39 UTC, stevecatherman approved these changes
Lovely.

2020-11-29 19:41 UTC, andrewdimmer approved these changes
Looks good to me! We may not even need the middle two tests, but we'll leave them in for now and take them out if we don't need them.

2020-11-29 19:41 UTC, andrewdimmer commented on docs/uml-class-diagrams/display01/test/DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests.puml
> +        + void elsePoorGpsSignalStrengths()
As we start building we may not need these two tests, but let's leave them in for now just in case.

2020-11-29 19:41 UTC, merged