Define-MiddlewareCommLinkManagerImplementationTests
andrewdimmer/csi-3370-software-project pull request #96
Opened 2020-11-28 16:28 UTC by kwillard34

closes #70

2020-11-28 17:26 UTC, andrewdimmer requested changes
Can we beef this up a bit more? I know this has a lot of your team's logic, so we should make sure that all of the code paths and functional requirements from the customer are covered in tests.

2020-11-28 17:26 UTC, andrewdimmer commented on docs/uml-class-diagrams/middleware02/test/MiddlewareCommLinkManagerImplementationTests/MiddlewareCommLinkManagerImplementationTests.puml
> +      + void verifyTrackLengthTest()
Note: you need a test cases for each and every function that your class does. I would take another look at the activity diagram and see if that helps you come up with more of the required test cases.

2020-11-28 21:42 UTC, mckenzieking approved these changes

2020-11-29 01:31 UTC, andrewdimmer requested changes

2020-11-29 01:31 UTC, andrewdimmer commented on docs/uml-class-diagrams/middleware02/test/MiddlewareCommLinkManagerImplementationTests/MiddlewareCommLinkManagerImplementationTests.puml
> +        + void storedDataCheck()
Just a few minor naming correction to better describe the tests, then you're all set to go!
```suggestion
        + void rfidDoesNotMatchStopsTestCase()
        + void storeRequestSent()
        + void emptyDatabaseReturnsEmptyTrackData()
        + void notEnoughDataReturnsPartialTrackData()
        + void enoughTrackDataReturnsFullData()
        + void commDatabaseInterfaceIsNotNull()
        + void gisManagerIsNotNull()
        + void storedTrackDataCheck()
```

2020-11-29 01:38 UTC, mckenzieking approved these changes

2020-11-29 01:38 UTC, andrewdimmer approved these changes
Looks good to me, you're all set to merge!

2020-11-29 01:38 UTC, merged